fpm:
  image:
    tag: main
    pullPolcy: Always

nginx:
  image:
    tag: main
    pullPolcy: Always
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/issuer: letsencrypt-production
    hosts:
      - host: portal.pbotapps-test.portland.gov
        paths:
          - path: /
    tls:
      - secretName: portal-pbotapps-test-portland-gov-tls
        hosts:
          - portal.pbotapps-test.portland.gov

files:
  storageClass: azurefile
  size: 8Gi
  accessModes:
    - ReadWriteMany

redis:
  persistence:
    enabled: true
    storageClass: managed-premium
    size: 8Gi
    accessModes:
      - ReadWriteOnce
