version: "3.3"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./artifacts:/docker-entrypoint-initdb.d"
      - "db:/var/lib/postgresql/data"
    networks:
      - code-network
      - db-network

  redis:
    image: redis
    networks:
      - cache-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
    volumes:
      - es:/usr/share/elasticsearch/data
    networks:
      - elastic-network


  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.10.2
    ports:
      - "5601:5601"
    networks:
      - elastic-network

  web:
    build:
      context: .docker/nginx
    environment:
      PANTHEON_ENVIRONMENT: dev
      FASTCGI_HOST: php
      FASTCGI_PORT: 9000
    ports:
      - "8888:80"
    volumes:
      - "./.docker/nginx/rootfs/etc/nginx/templates:/etc/nginx/templates:cached"
      - ".:/var/www/html:cached"
    networks:
      - code-network
      - cache-network

  php:
    build:
      context: .docker/php
      args:
        INSTALL_XDEBUG: "true"
        INSTALL_COMPOSER: "true"
    user: www-data
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      CACHE_HOST: redis
      CACHE_PORT: 6379
      ELASTICSEARCH_URL: http://elasticsearch:9200
      DRUPAL_ENV: development
      XDEBUG_CONFIG: mode=debug client_host=host.docker.internal start_with_request=yes
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
    volumes:
      - ".:/var/www/html:cached"
    networks:
      - code-network
      - cache-network
      - db-network
      - elastic-network

networks:
  code-network:
    driver: bridge
  db-network:
    driver: bridge
  cache-network:
    driver: bridge
  elastic-network:
    driver: bridge

volumes:
  tmp:
  db:
  es:
