{{- $fullName := include "portal.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portal.fullname" . }}-nginx
  labels:
    {{- include "portal.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/component: nginx
spec:
  {{- if not .Values.nginx.autoscaling.enabled }}
  replicas: {{ .Values.nginx.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "portal.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/part-of: {{ .Chart.Name }}
      app.kubernetes.io/component: nginx
  template:
    metadata:
      {{- with .Values.nginx.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "portal.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/part-of: {{ .Chart.Name }}
        app.kubernetes.io/component: nginx
    spec:
      {{- with .Values.nginx.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "portal.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.nginx.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.nginx.securityContext | nindent 12 }}
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: FASTCGI_HOST
              value: {{ include "portal.fullname" . }}-fpm
            - name: FASTCGI_PORT
              value: "{{ .Values.fpm.service.port }}"
          volumeMounts:
            {{ range $key, $val := .Values.sites -}}
            - name: files-{{ $key }}
              mountPath: /var/www/html/web/sites/{{ $key }}/files
            {{ end }}
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
      volumes:
        {{ range $key, $val := .Values.sites -}}
        - name: files-{{ $key }}
          persistentVolumeClaim:
            claimName: {{ $fullName }}-{{ $key }}-files
        {{ end }}
      {{- with .Values.nginx.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nginx.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nginx.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
