{{- if .Values.airflow.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "portal.fullname" . }}-fpm-env"
  labels:
    {{- include "portal.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/component: fpm
data:
  DATABASE_HOST: {{ .Values.postgresql.host }}
  DATABASE_USER: {{ .Values.postgresql.user }}
  ELASTICSEARCH_URL: {{ .Values.elasticsearch.url }}
  CACHE_HOST: {{ include "portal.fullname" . }}-redis
  CACHE_PORT: "{{ .Values.redis.service.port }}"
  sites.php: |-
    <?php
    $sites['portal.pbotapps.portland.gov.comms'] = 'comms';
    $sites['portal.pbotapps.portland.gov'] = 'default';


{{- end -}}
