apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "portal.fullname" . }}-fpm"
  labels:
    {{- include "portal.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/component: fpm
data:
  CACHE_HOST: {{ include "portal.fullname" . }}-redis
  CACHE_PORT: "{{ .Values.redis.service.port }}"
  DATABASE_HOST: {{ .Values.postgresql.host }}
  DATABASE_USER: {{ .Values.postgresql.user }}
  DRUPAL_ENV: production
  ELASTICSEARCH_URL: {{ .Values.elasticsearch.url }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "portal.fullname" . }}-fpm-sites"
  labels:
    {{- include "portal.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/component: fpm
data:
  sites.php: |
    <?php

    {{- $self := . -}}
    {{- range $key, $val := .Values.sites -}}
    {{- range $host := $self.Values.nginx.ingress.hosts -}}
    {{- if eq $key "default" }}
    $sites['{{ $host.host }}'] = '{{ $key }}';
    {{- else }}
    $sites['{{ $host.host }}.{{ $key }}'] = '{{ $key }}';
    {{- end }}
    {{- end }}
    {{- end }}
