apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portal.fullname" . }}-fpm
  labels:
    {{- include "portal.labels" . | nindent 4 }}
spec:
  {{- if not .Values.fpm.autoscaling.enabled }}
  replicas: {{ .Values.fpm.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "portal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.fpm.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "portal.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.fpm.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "portal.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.fpm.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.fpm.securityContext | nindent 12 }}
          image: "{{ .Values.fpm.image.repository }}:{{ .Values.fpm.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.fpm.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.fpm.resources | nindent 12 }}
      {{- with .Values.fpm.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fpm.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fpm.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
