apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portal.fullname" . }}-fpm
  labels:
    {{- include "portal.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/component: fpm
type: Opaque
data:
  DATABASE_PASSWORD: {{ .Files.Get ".secret/DATABASE_PASSWORD" | b64enc | quote }}
  AZURE_CLIENT_ID: {{ .Files.Get ".secret/AZURE_CLIENT_ID" | b64enc | quote }}
  AZURE_CLIENT_SECRET: {{ .Files.Get ".secret/AZURE_CLIENT_SECRET" | b64enc | quote }}
  SENDGRID_API_KEY: {{ .Files.Get ".secret/SENDGRID_API_KEY" | b64enc | quote }}
  public.key: {{ .Files.Get ".secret/public.key" | b64enc | quote }}
  private.key: {{ .Files.Get ".secret/private.key" | b64enc | quote }}
