apiVersion: v1
kind: Service
metadata:
  name: {{ include "portal.fullname" . }}-fpm
  labels:
    {{- include "portal.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/component: fpm
spec:
  type: {{ .Values.fpm.service.type }}
  ports:
    - port: {{ .Values.fpm.service.port }}
      targetPort: fpm
      protocol: TCP
      name: fpm
  selector:
    {{- include "portal.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/component: fpm
